### ISSUE TITLE
WP-3821 CP-3449 Possible Task Runner Improvements

### ISSUE THREAD

**Issue by todbachman-wf** [Workiva/dart_dev#208]
The new task runner is awesome! However, it does have a couple of downsides:

1. You can't see the task output as the task runner is running
2. If one task fails you have to wait for all of the tasks to complete before Smithy detects the failure
3. The output is not as easy to sort through as it used to be

I think the improved runtime of Smithy outweighs these downsides, but if we can address some of these I think more devs will be onboard with using it.

**Comment by rmconsole3-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/dart_dev/208/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by jayudey-wf** [comment]
just a few quick follow up questions?

1. How would you like to see the output as the tasks are running? since the tasks are running concurrently the output would be kind of _jumbled_ together, would that be what you are looking for?
2. In the case of a failure would you like to see the current status of all the other tasks?
3. What would make the output more easily consumable at the end, more indentations or logical white spacing?

**Comment by maxwellpeterson-wf** [comment]
For #1 - Could potentially print the output for a task once it finishes - I think SOX does this (or rather, `make` accomplishes this for them).

For #3 - I think it would be nice to print both stdout and stderr (currently only printing stderr) for the fail task at the bottom.

**Comment by todbachman-wf** [comment]
I concur with Max. And for #2, it would be great if we could see the
current status of all the other tasks too!

**Comment by maxwellpeterson-wf** [comment]
Closing as addressed in #215
