### ISSUE TITLE
CP-2145 Uncaught Error: Exception: Coverage formatting failed. 

### ISSUE THREAD

**Issue by rayk** [Workiva/dart_dev#50]
Guys love the idea of ddev... Hopefully by endless grinder task can go away..

Anyhow run into this problem

```
ddev coverage

::: Collecting coverage

    Running test suite test/cxs_store_test.dart
    dart --observe=56484 test/cxs_store_test.dart

        Observatory listening on http://127.0.0.1:56484
        00:00 +0: A group of tests First Test
        00:00 +1: All tests passed!

    Collecting coverage for test/cxs_store_test.dart
    pub run coverage:collect_coverage --port=56484 -o coverage/collection/test/cxs_store_test.dart.json
    Formatting coverage
    pub run coverage:format_coverage -l --package-root=packages -i coverage/coverage.json -o coverage/coverage.lcov --verbose --report-on=lib/


        Provided package root "packages" is not directory.

        Usage: dart format_coverage.dart [OPTION...]

        -s, --sdk-root        path to the SDK root
        -p, --package-root    path to the package root
        -i, --in              input(s): may be file or directory
        -o, --out             output: may be file or stdout
                              (defaults to "stdout")

            --report-on       which directories or files to report coverage on
        -j, --workers         number of workers
                              (defaults to "1")

        -r, --pretty-print    convert coverage data to pretty print format
        -l, --lcov            convert coverage data to lcov format
        -v, --verbose         verbose output
        -h, --help            show this help
    Coverage formatting failed. Could not generate coverage/coverage.lcov
Unhandled exception:
Uncaught Error: Exception: Coverage formatting failed. Could not generate coverage/coverage.lcov
Stack Trace:
#0      CoverageTask._format.<_format_async_body> (package:dart_dev/src/tasks/coverage/api.dart:280:7)
#1      _RootZone.runUnary (dart:async/zone.dart:1166)
#2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#3      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#4      _Future._completeWithValue (dart:async/future_impl.dart:368)
#5      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#7      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```
## Dart Version

Dart VM version: 1.12.0-dev.5.9 (Mon Aug 24 03:56:54 2015) on "macos_x64"
## Description

I can make this happen consistently, if you use [stagehand](https://pub.dartlang.org/packages/stagehand) to set a `package-simple` project. You will certain hit the problem.

Thanks in advance and keep the work... Just need a way to run dart_doc now.

**Comment by evanweible-wf** [comment]
Looks like this is because dart 1.12 removes the packages directory in favor of a single `.packages` file in the root. The [coverage package](https://github.com/dart-lang/coverage) uses a `--package-root` option for the format task. I'll investigate if omitting that option altogether fixes the problem for projects with the newer packages format, but it may require a change to the coverage package as well.

I've got an issue open for running dart_doc - you can follow it here: #26 

Thanks for interest in the project @rayk and keep the feedback coming!

**Comment by evanweible-wf** [comment]
At this point I don't think there's anything we can do since 1.12 hasn't hit stable yet and the dependencies we use to run tests and coverage don't support it yet, either. I've opened an issue with the coverage package (https://github.com/dart-lang/coverage/issues/100) and there is already an issue open with the test package (https://github.com/dart-lang/test/issues/327). I'll update this issue as things progress.

**Comment by evanweible-wf** [comment]
Coverage works with Dart 1.12 as long as you're not using the `--no-package-symlinks` flag with `pub`. I'm keeping this issue open until https://github.com/dart-lang/coverage/issues/100 is resolved and I can confirm that this works even when using `--no-package-symlinks`, but I'm removing it from the 1.0.1 milestone since there's nothing to do at this moment.
