### ISSUE TITLE
CP-2135 Coverage: fail (but still complete) task if one or more test suites fail

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/dart_dev#73]
Currently the logs will display an error noting when a test suite fails, but the coverage is simply ignored for that suite and the overall coverage task still succeeds. This produces a coverage report with lower-than-expected coverage.

**Comment by greglittlefield-wf** [comment]
Any updates on this? Being able to run just coverage instead of tests+coverage would allow us to shave 9 minutes off our CI build. Which would be really nice 😃 .

Could we do something like grep the logs for that error message and set the exit code accordingly? A little hacky, but we should be fine as long as we have solid test coverage.

**Comment by maxwellpeterson-wf** [comment]
@greglittlefield-wf are you using a test entry points (`unit_tests.dart`, `integration_tests.dart`) or is each file being loaded into coverage separately? That's a big area for improvement if not.

Besides that, you could look into running coverage in the background: https://github.com/Workiva/tasker-ui/blob/master/smithy.yaml#L17

**Comment by greglittlefield-wf** [comment]
@maxwellpeterson-wf We are running each of our 5 test entry points separately, since combining them results in test loading timeouts (see https://github.com/dart-lang/test/issues/390).

Running in the background is a good idea; we'll give that a whirl, thanks! Hopefully that'll give us a decent speedup.

**Comment by evanweible-wf** [comment]
@greglittlefield-wf even if this issue was fixed, I still wouldn't recommend relying on the coverage run alone. Historically it's been too brittle and I'm not as confident in it as I am the test package.

**Comment by greglittlefield-wf** [comment]
<img title=(okay) alt=(okay) height=25 src="https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/okay-1414023544@2x.png">

**Comment by greglittlefield-wf** [comment]
As an update, trying to run coverage/tests at the same time or separately during other parts of the build result in slowdowns that lead to that same timeout issue :(.
